name: Release Android

on:
  push:
    tags:
      - '*'

env:
  RELEASE_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
  SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  DEBUG_KEY_STORE_BASE64: ${{ secrets.DEBUG_SIGNING_KEY_BASE64 }}
  EXPORT_PRESET_CFG: ${{ secrets.GODOT_EXPORTS_PRESET_CFG }}
  WORKING_DIRECTORY: game

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create service-account.json
        run: echo $SERVICE_ACCOUNT_JSON > service-account.json

      - name: Create release keystore
        run: echo $RELEASE_KEY_STORE_BASE64 | base64 --decode > keystore.keystore

      - name: Create debug keystore
        run: echo $DEBUG_KEY_STORE_BASE64 | base64 --decode > debug.keystore

      - name: Set version number and version code. Git tag must be 4.0.1-68
        run: |
          echo "VERSION_NAME=$(echo ${{ github.ref_name }} | cut -f1 -d-)" >> $GITHUB_ENV
          echo "VERSION_CODE=$(echo ${{ github.ref_name }} | cut -f2 -d-)" >> $GITHUB_ENV

      - name: Create and config export_presets.cfg
        run: |
          echo $EXPORT_PRESET_CFG > $WORKING_DIRECTORY/export_presets.cfg
          sed -i "s|KEYSTORE_PATH|$GITHUB_WORKSPACE/keystore.keystore|g" $WORKING_DIRECTORY/export_presets.cfg
          sed -i "s|VERSION_CODE|$VERSION_NAME|g" $WORKING_DIRECTORY/export_presets.cfg
          sed -i "s|VERSION_NAME|$VERSION_NAME|g" $WORKING_DIRECTORY/export_presets.cfg

      - name: Export signed apk and release to internal testing
        uses: dulvui/godot-android-release@v1
        with:
          working-directory: $WORKING_DIRECTORY
          package-name: com.salvai.broomball
          release-file: ./Broomball.apk
          version-code: ${{ env.VERSION_CODE }}
          version-name: ${{ env.VERSION_NAME }}