name: Release

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set version number and version code. Git tag must be 4.0.1-68
        run: |
          echo "VERSION_NAME=$(echo ${{ github.ref_name }} | cut -f1 -d-)" >> $GITHUB_ENV
          echo "VERSION_CODE=$(echo ${{ github.ref_name }} | cut -f2 -d-)" >> $GITHUB_ENV

      - name: Release to internal testing
        uses: dulvui/godot-android-release@v1
        with:
          working-directory: game
          package-name: com.salvai.broomball
          service-account-json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          release-file: ./Broomball.apk
          export-preset-cfg: ${{ secrets.GODOT_EXPORTS_PRESET_CFG }}
          release-signing-key-base64: ${{ secrets.SIGNING_KEY_BASE64 }}
          debug-signing-key-base64: ${{ secrets.DEBUG_SIGNING_KEY_BASE64 }}
          version-code: ${{ env.VERSION_CODE }}
          version-name: ${{ env.VERSION_NAME }}