name: Release

on: 
  push:

env:
  SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
  GODOT_EXPORTS_PRESET_CFG: ${{ secrets.GODOT_EXPORTS_PRESET_CFG }}
  WORKING_DIRECTORY: game

jobs:
  deploy:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: create service-account.json
        run: echo $SERVICE_ACCOUNT_JSON > service-account.json

      - name: Create export_presets.cfg
        run: echo $GODOT_EXPORTS_PRESET_CFG > $WORKING_DIRECTORY/export_presets.cfg

      - name: Create keystore
        run: echo $SIGNING_KEY_BASE64 | base64 --decode > keystore.keystore

      - name: Add keystore path to export_presets.cfg
        run: echo $GITHUB_WORKSPACE/keystore.keystore >> $WORKING_DIRECTORY/export_presets.cfg

      - name: Add version to export_presets.cfg [HARDCODED FOR NOW...]
        run: |
          echo "version/code=68" >> $WORKING_DIRECTORY/export_presets.cfg
          echo "version/name="4.0.3"" >> $WORKING_DIRECTORY/export_presets.cfg
      
      - name: ls and cat 
        run: |
          ls $WORKING_DIRECTORY
          cat $WORKING_DIRECTORY/export_presets.cfg


      - name: Release to internal testing
        uses: dulvui/godot-android-release@v1
        with:
          working-directory: $WORKING_DIRECTORY
          package-name: com.salvai.broomball
          service-account-json: $GOOGLE_SERVICE_ACCOUNT_JSON
          release-file: ./Broomball.apk
